import type { InterventionOption, InterventionState, LogEntry } from "../types";

type Props = {
  logs: LogEntry[];
  systemLog: string[];
  intervention: InterventionState | null;
  interventionLoading: boolean;
  remainingSec: number;
  alexTraits: { diligence: number; invention: number };
  soilGreenhouse: string;
  cropPolicy: string | null;
  onChooseOption: (id: string) => void;
};

function typeLabel(t: InterventionOption["type"]) {
  if (t === "narrative") return "叙述 Narrative";
  if (t === "system") return "系统 System";
  return "个性 Personality";
}

export function RightPanel({
  logs,
  systemLog,
  intervention,
  interventionLoading,
  remainingSec,
  alexTraits,
  soilGreenhouse,
  cropPolicy,
  onChooseOption,
}: Props) {
  return (
    <aside className="panel panel--right panel--stack">
      <section className="agents-strip">
        <h2>AI Agents</h2>
        <div className="agents-row">
          <div className="agent-chip agent-chip--alex">Alex</div>
          <div className="agent-chip agent-chip--mia">Mia</div>
        </div>
        <div className="traits-mini">
          Alex 勤劳 {Math.round(alexTraits.diligence)} · 发明 {Math.round(alexTraits.invention)}
        </div>
        <div className="traits-mini">温室旁土壤：{soilGreenhouse}</div>
        {cropPolicy ? <div className="traits-mini">政策：{cropPolicy}</div> : null}
      </section>

      <section className="proposal-panel">
        <div className="proposal-panel__head">
          <h2>AI FUTURE PROPOSAL</h2>
          <span className="proposal-panel__badge">GENERATED BY LLM</span>
        </div>
        {interventionLoading ? (
          <p className="proposal-panel__loading">正在生成提案…</p>
        ) : intervention ? (
          <>
            <div className="intervention-window">
              PLAYER INTERVENTION WINDOW: <strong>{remainingSec}</strong>S
            </div>
            <ul className="proposal-options">
              {intervention.payload.options.map((opt) => (
                <li key={opt.id}>
                  <button type="button" className="proposal-option" onClick={() => onChooseOption(opt.id)}>
                    <span className="proposal-option__type">{typeLabel(opt.type)}</span>
                    <span className="proposal-option__title">{opt.titleZh}</span>
                    <span className="proposal-option__sub">{opt.titleEn}</span>
                    <p className="proposal-option__desc">{opt.descriptionZh}</p>
                  </button>
                </li>
              ))}
            </ul>
            <p className="proposal-panel__hint">未选择时，倒计时结束后由 AI 依 NPC 个性自动执行。</p>
          </>
        ) : (
          <p className="proposal-panel__idle">等待下一轮介入窗口（游戏内事件冷却中）…</p>
        )}
      </section>

      <section className="log-section">
        <h2>日志</h2>
        <ul className="log-list">
          {logs.map((log, i) => (
            <li key={`${log.time}-${i}-${log.text.slice(0, 8)}`}>
              {log.strong ? (
                <>
                  <strong>[{log.time}]</strong> {log.text}
                </>
              ) : (
                <>
                  [{log.time}] {log.text}
                </>
              )}
            </li>
          ))}
        </ul>
      </section>

      <section className="log-section log-section--system">
        <h2>SYSTEM UPDATE LOG</h2>
        <ul className="log-list log-list--system">
          {systemLog.map((line, i) => (
            <li key={`${i}-${line.slice(0, 12)}`}>{line}</li>
          ))}
        </ul>
      </section>
    </aside>
  );
}
